package entity

import "time"

type OfflineMessage struct {
	ID                       int64   `json:"id"`
	DateTime                 string  `json:"date_time"`
	Text                     string  `json:"text"`
	CommunicationNumber      int64   `json:"communication_number"`
	CommunicationPageURL     string  `json:"communication_page_url"`
	CommunicationType        string  `json:"communication_type"`
	CommunicationID          int64   `json:"communication_id"`
	UaClientID               string  `json:"ua_client_id"`
	YmClientID               string  `json:"ym_client_id"`
	SaleDate                 string  `json:"sale_date"`
	SaleCost                 float64 `json:"sale_cost"`
	Status                   string  `json:"status"`
	ProcessTime              string  `json:"process_time"`
	FormType                 string  `json:"form_type"`
	FormName                 string  `json:"form_name"`
	SearchQuery              string  `json:"search_query"`
	SearchEngine             string  `json:"search_engine"`
	ReferrerDomain           string  `json:"referrer_domain"`
	Referrer                 string  `json:"referrer"`
	EntrancePage             string  `json:"entrance_page"`
	Gclid                    string  `json:"gclid"`
	Yclid                    string  `json:"yclid"`
	Ymclid                   string  `json:"ymclid"`
	EfID                     string  `json:"ef_id"`
	Channel                  string  `json:"channel"`
	EmployeeID               int64   `json:"employee_id"`
	EmployeeFullName         string  `json:"employee_full_name"`
	EmployeeAnswerMessage    string  `json:"employee_answer_message"`
	EmployeeComment          string  `json:"employee_comment"`
	Tags                     string  `json:"tags"`
	SiteID                   int64   `json:"site_id"`
	SiteDomainName           string  `json:"site_domain_name"`
	GroupID                  int64   `json:"group_id"`
	GroupName                string  `json:"group_name"`
	CampaignID               int64   `json:"campaign_id"`
	CampaignName             string  `json:"campaign_name"`
	VisitOtherCampaign       bool    `json:"visit_other_campaign"`
	VisitorID                int64   `json:"visitor_id"`
	VisitorName              string  `json:"visitor_name"`
	VisitorPhoneNumber       string  `json:"visitor_phone_number"`
	VisitorEmail             string  `json:"visitor_email"`
	PersonID                 int64   `json:"person_id"`
	VisitorType              string  `json:"visitor_type"`
	VisitorSessionID         int64   `json:"visitor_session_id"`
	VisitsCount              int64   `json:"visits_count"`
	VisitorFirstCampaignID   int64   `json:"visitor_first_campaign_id"`
	VisitorFirstCampaignName string  `json:"visitor_first_campaign_name"`
	VisitorCity              string  `json:"visitor_city"`
	VisitorRegion            string  `json:"visitor_region"`
	VisitorCountry           string  `json:"visitor_country"`
	VisitorDevice            string  `json:"visitor_device"`
	UtmSource                string  `json:"utm_source"`
	UtmMedium                string  `json:"utm_medium"`
	UtmTerm                  string  `json:"utm_term"`
	UtmContent               string  `json:"utm_content"`
	UtmCampaign              string  `json:"utm_campaign"`
	OpenStatAd               string  `json:"openstat_ad"`
	OpenStatCampaign         string  `json:"openstat_campaign"`
	OpenStatService          string  `json:"openstat_service"`
	OpenStatSource           string  `json:"openstat_source"`
	EqUtmSource              string  `json:"eq_utm_source"`
	EqUtmMedium              string  `json:"eq_utm_medium"`
	EqUtmTerm                string  `json:"eq_utm_term"`
	EqUtmContent             string  `json:"eq_utm_content"`
	EqUtmCampaign            string  `json:"eq_utm_campaign"`
	EqUtmReferrer            string  `json:"eq_utm_referrer"`
	EqUtmExpid               string  `json:"eq_utm_expid"`
	Attributes               string  `json:"attributes"`
	SourceID                 int64   `json:"source_id"`
	SourceName               string  `json:"source_name"`
	SourceNew                string  `json:"source_new"`
	ChannelNew               string  `json:"channel_new"`
	ChannelCode              string  `json:"channel_code"`
	DateUpdate               time.Time
}

type OfflineMessageCSV struct {
	ID                       int64   `csv:"id"`
	Date                     string  `csv:"date"`
	DateTime                 string  `csv:"date_time"`
	Text                     string  `csv:"text"`
	CommunicationNumber      int64   `csv:"communication_number"`
	CommunicationPageURL     string  `csv:"communication_page_url"`
	CommunicationType        string  `csv:"communication_type"`
	CommunicationID          int64   `csv:"communication_id"`
	UaClientID               string  `csv:"ua_client_id"`
	YmClientID               string  `csv:"ym_client_id"`
	SaleDate                 string  `csv:"sale_date"`
	SaleCost                 float64 `csv:"sale_cost"`
	Status                   string  `csv:"status"`
	ProcessTime              string  `csv:"process_time"`
	FormType                 string  `csv:"form_type"`
	FormName                 string  `csv:"form_name"`
	SearchQuery              string  `csv:"search_query"`
	SearchEngine             string  `csv:"search_engine"`
	ReferrerDomain           string  `csv:"referrer_domain"`
	Referrer                 string  `csv:"referrer"`
	EntrancePage             string  `csv:"entrance_page"`
	Gclid                    string  `csv:"gclid"`
	Yclid                    string  `csv:"yclid"`
	Ymclid                   string  `csv:"ymclid"`
	EfID                     string  `csv:"ef_id"`
	Channel                  string  `csv:"channel"`
	EmployeeID               int64   `csv:"employee_id"`
	EmployeeFullName         string  `csv:"employee_full_name"`
	EmployeeAnswerMessage    string  `csv:"employee_answer_message"`
	EmployeeComment          string  `csv:"employee_comment"`
	Tags                     string  `csv:"tags"`
	SiteID                   int64   `csv:"site_id"`
	SiteDomainName           string  `csv:"site_domain_name"`
	GroupID                  int64   `csv:"group_id"`
	GroupName                string  `csv:"group_name"`
	CampaignID               int64   `csv:"campaign_id"`
	CampaignName             string  `csv:"campaign_name"`
	VisitOtherCampaign       bool    `csv:"visit_other_campaign"`
	VisitorID                int64   `csv:"visitor_id"`
	VisitorName              string  `csv:"visitor_name"`
	VisitorPhoneNumber       string  `csv:"visitor_phone_number"`
	VisitorEmail             string  `csv:"visitor_email"`
	PersonID                 int64   `csv:"person_id"`
	VisitorType              string  `csv:"visitor_type"`
	VisitorSessionID         int64   `csv:"visitor_session_id"`
	VisitsCount              int64   `csv:"visits_count"`
	VisitorFirstCampaignID   int64   `csv:"visitor_first_campaign_id"`
	VisitorFirstCampaignName string  `csv:"visitor_first_campaign_name"`
	VisitorCity              string  `csv:"visitor_city"`
	VisitorRegion            string  `csv:"visitor_region"`
	VisitorCountry           string  `csv:"visitor_country"`
	VisitorDevice            string  `csv:"visitor_device"`
	UtmSource                string  `csv:"utm_source"`
	UtmMedium                string  `csv:"utm_medium"`
	UtmTerm                  string  `csv:"utm_term"`
	UtmContent               string  `csv:"utm_content"`
	UtmCampaign              string  `csv:"utm_campaign"`
	OpenStatAd               string  `csv:"openstat_ad"`
	OpenStatCampaign         string  `csv:"openstat_campaign"`
	OpenStatService          string  `csv:"openstat_service"`
	OpenStatSource           string  `csv:"openstat_source"`
	EqUtmSource              string  `csv:"eq_utm_source"`
	EqUtmMedium              string  `csv:"eq_utm_medium"`
	EqUtmTerm                string  `csv:"eq_utm_term"`
	EqUtmContent             string  `csv:"eq_utm_content"`
	EqUtmCampaign            string  `csv:"eq_utm_campaign"`
	EqUtmReferrer            string  `csv:"eq_utm_referrer"`
	EqUtmExpid               string  `csv:"eq_utm_expid"`
	Attributes               string  `csv:"attributes"`
	SourceID                 int64   `csv:"source_id"`
	SourceName               string  `csv:"source_name"`
	SourceNew                string  `csv:"source_new"`
	ChannelNew               string  `csv:"channel_new"`
	ChannelCode              string  `csv:"channel_code"`
	DateUpdate               string  `csv:"date_update"`
}
