keys_dir: "/path/to/keys" // Путь к папке с сервисными ключами
prometheus_addr: localhost:9090

grpc:
  ip: "0.0.0.0"           // Host
  port: 50051             // Порт, который будет прослушивать сервис

comagic:
  version: "2.0"          // Версия DataApi Comagic (текущая 2.0)

tg:
  token: 'TG Token'       // Токен для telegram бота
  chat: 0000000000        // ID чата в который будут отправляться уведомления
  is_enabled: false       // Статус уведомлений