// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/grpc/comagic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Конфигурация для BigQuery
type BqConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId  string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DatasetId  string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	TableId    string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	ServiceKey string `protobuf:"bytes,4,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"` // Название файла сервисного ключа
}

func (x *BqConfig) Reset() {
	*x = BqConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqConfig) ProtoMessage() {}

func (x *BqConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqConfig.ProtoReflect.Descriptor instead.
func (*BqConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{0}
}

func (x *BqConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BqConfig) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *BqConfig) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *BqConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

// Конфигурация для CloudStorage
type CsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceKey string `protobuf:"bytes,1,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	BucketName string `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"` // Название файла сервисного ключа
}

func (x *CsConfig) Reset() {
	*x = CsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsConfig) ProtoMessage() {}

func (x *CsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsConfig.ProtoReflect.Descriptor instead.
func (*CsConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{1}
}

func (x *CsConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *CsConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateFrom string `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTill string `protobuf:"bytes,2,opt,name=date_till,json=dateTill,proto3" json:"date_till,omitempty"`
}

func (x *Period) Reset() {
	*x = Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{2}
}

func (x *Period) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *Period) GetDateTill() string {
	if x != nil {
		return x.DateTill
	}
	return ""
}

type PushCallsToBQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string    `protobuf:"bytes,1,opt,name=comagic_token,json=comagicToken,proto3" json:"comagic_token,omitempty"` // required
	BqConfig     *BqConfig `protobuf:"bytes,2,opt,name=bq_config,json=bqConfig,proto3" json:"bq_config,omitempty"`             // required Конфигурация для BigQuery
	CsConfig     *CsConfig `protobuf:"bytes,3,opt,name=cs_config,json=csConfig,proto3" json:"cs_config,omitempty"`             // required Конфигурация для CloudStorage
	Period       *Period   `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`                                 // required
}

func (x *PushCallsToBQRequest) Reset() {
	*x = PushCallsToBQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCallsToBQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCallsToBQRequest) ProtoMessage() {}

func (x *PushCallsToBQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCallsToBQRequest.ProtoReflect.Descriptor instead.
func (*PushCallsToBQRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{3}
}

func (x *PushCallsToBQRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

func (x *PushCallsToBQRequest) GetBqConfig() *BqConfig {
	if x != nil {
		return x.BqConfig
	}
	return nil
}

func (x *PushCallsToBQRequest) GetCsConfig() *CsConfig {
	if x != nil {
		return x.CsConfig
	}
	return nil
}

func (x *PushCallsToBQRequest) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

type PushCallsToBQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *PushCallsToBQResponse) Reset() {
	*x = PushCallsToBQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCallsToBQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCallsToBQResponse) ProtoMessage() {}

func (x *PushCallsToBQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCallsToBQResponse.ProtoReflect.Descriptor instead.
func (*PushCallsToBQResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{4}
}

func (x *PushCallsToBQResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type PushOfflineMessagesToBQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string    `protobuf:"bytes,1,opt,name=comagic_token,json=comagicToken,proto3" json:"comagic_token,omitempty"` // required
	BqConfig     *BqConfig `protobuf:"bytes,2,opt,name=bq_config,json=bqConfig,proto3" json:"bq_config,omitempty"`             // required Конфигурация для BigQuery
	CsConfig     *CsConfig `protobuf:"bytes,3,opt,name=cs_config,json=csConfig,proto3" json:"cs_config,omitempty"`             // required Конфигурация для CloudStorage
	Period       *Period   `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`                                 // required
}

func (x *PushOfflineMessagesToBQRequest) Reset() {
	*x = PushOfflineMessagesToBQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOfflineMessagesToBQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOfflineMessagesToBQRequest) ProtoMessage() {}

func (x *PushOfflineMessagesToBQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOfflineMessagesToBQRequest.ProtoReflect.Descriptor instead.
func (*PushOfflineMessagesToBQRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{5}
}

func (x *PushOfflineMessagesToBQRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

func (x *PushOfflineMessagesToBQRequest) GetBqConfig() *BqConfig {
	if x != nil {
		return x.BqConfig
	}
	return nil
}

func (x *PushOfflineMessagesToBQRequest) GetCsConfig() *CsConfig {
	if x != nil {
		return x.CsConfig
	}
	return nil
}

func (x *PushOfflineMessagesToBQRequest) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

type PushOfflineMessagesToBQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *PushOfflineMessagesToBQResponse) Reset() {
	*x = PushOfflineMessagesToBQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOfflineMessagesToBQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOfflineMessagesToBQResponse) ProtoMessage() {}

func (x *PushOfflineMessagesToBQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOfflineMessagesToBQResponse.ProtoReflect.Descriptor instead.
func (*PushOfflineMessagesToBQResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{6}
}

func (x *PushOfflineMessagesToBQResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type GetCampaignsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string `protobuf:"bytes,1,opt,name=comagic_token,json=comagicToken,proto3" json:"comagic_token,omitempty"`
}

func (x *GetCampaignsRequest) Reset() {
	*x = GetCampaignsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsRequest) ProtoMessage() {}

func (x *GetCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{7}
}

func (x *GetCampaignsRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

type GetCampaignsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCampaignsResponse) Reset() {
	*x = GetCampaignsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsResponse) ProtoMessage() {}

func (x *GetCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{8}
}

type GetCampaignsConditionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string `protobuf:"bytes,1,opt,name=comagic_token,json=comagicToken,proto3" json:"comagic_token,omitempty"`
}

func (x *GetCampaignsConditionsRequest) Reset() {
	*x = GetCampaignsConditionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsConditionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsConditionsRequest) ProtoMessage() {}

func (x *GetCampaignsConditionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsConditionsRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignsConditionsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{9}
}

func (x *GetCampaignsConditionsRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

type GetCampaignsConditionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCampaignsConditionsResponse) Reset() {
	*x = GetCampaignsConditionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsConditionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsConditionsResponse) ProtoMessage() {}

func (x *GetCampaignsConditionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsConditionsResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignsConditionsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{10}
}

var File_api_grpc_comagic_proto protoreflect.FileDescriptor

var file_api_grpc_comagic_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x22, 0x84, 0x01, 0x0a, 0x08, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x4c, 0x0a, 0x08, 0x43, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x6c, 0x22, 0xc4, 0x01, 0x0a, 0x14, 0x50,
	0x75, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61,
	0x67, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x09, 0x62, 0x71, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f,
	0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08,
	0x62, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x73, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f,
	0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x43, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08,
	0x63, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x22, 0x2c, 0x0a, 0x15, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f,
	0x42, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73,
	0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x22,
	0xce, 0x01, 0x0a, 0x1e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x09, 0x62, 0x71, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d,
	0x61, 0x67, 0x69, 0x63, 0x2e, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x62,
	0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x73, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d,
	0x61, 0x67, 0x69, 0x63, 0x2e, 0x43, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x63,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x22, 0x36, 0x0a, 0x1f, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x22, 0x3a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x86, 0x03, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x43,
	0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x17, 0x50, 0x75, 0x73, 0x68, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f,
	0x42, 0x51, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x6f,
	0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x69, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x2e, 0x63,
	0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69,
	0x67, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_comagic_proto_rawDescOnce sync.Once
	file_api_grpc_comagic_proto_rawDescData = file_api_grpc_comagic_proto_rawDesc
)

func file_api_grpc_comagic_proto_rawDescGZIP() []byte {
	file_api_grpc_comagic_proto_rawDescOnce.Do(func() {
		file_api_grpc_comagic_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_comagic_proto_rawDescData)
	})
	return file_api_grpc_comagic_proto_rawDescData
}

var file_api_grpc_comagic_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_grpc_comagic_proto_goTypes = []interface{}{
	(*BqConfig)(nil),                        // 0: comagic.BqConfig
	(*CsConfig)(nil),                        // 1: comagic.CsConfig
	(*Period)(nil),                          // 2: comagic.Period
	(*PushCallsToBQRequest)(nil),            // 3: comagic.PushCallsToBQRequest
	(*PushCallsToBQResponse)(nil),           // 4: comagic.PushCallsToBQResponse
	(*PushOfflineMessagesToBQRequest)(nil),  // 5: comagic.PushOfflineMessagesToBQRequest
	(*PushOfflineMessagesToBQResponse)(nil), // 6: comagic.PushOfflineMessagesToBQResponse
	(*GetCampaignsRequest)(nil),             // 7: comagic.GetCampaignsRequest
	(*GetCampaignsResponse)(nil),            // 8: comagic.GetCampaignsResponse
	(*GetCampaignsConditionsRequest)(nil),   // 9: comagic.GetCampaignsConditionsRequest
	(*GetCampaignsConditionsResponse)(nil),  // 10: comagic.GetCampaignsConditionsResponse
}
var file_api_grpc_comagic_proto_depIdxs = []int32{
	0,  // 0: comagic.PushCallsToBQRequest.bq_config:type_name -> comagic.BqConfig
	1,  // 1: comagic.PushCallsToBQRequest.cs_config:type_name -> comagic.CsConfig
	2,  // 2: comagic.PushCallsToBQRequest.period:type_name -> comagic.Period
	0,  // 3: comagic.PushOfflineMessagesToBQRequest.bq_config:type_name -> comagic.BqConfig
	1,  // 4: comagic.PushOfflineMessagesToBQRequest.cs_config:type_name -> comagic.CsConfig
	2,  // 5: comagic.PushOfflineMessagesToBQRequest.period:type_name -> comagic.Period
	3,  // 6: comagic.ComagicService.PushCallsToBQ:input_type -> comagic.PushCallsToBQRequest
	5,  // 7: comagic.ComagicService.PushOfflineMessagesToBQ:input_type -> comagic.PushOfflineMessagesToBQRequest
	7,  // 8: comagic.ComagicService.GetCampaigns:input_type -> comagic.GetCampaignsRequest
	9,  // 9: comagic.ComagicService.GetCampaignsConditions:input_type -> comagic.GetCampaignsConditionsRequest
	4,  // 10: comagic.ComagicService.PushCallsToBQ:output_type -> comagic.PushCallsToBQResponse
	6,  // 11: comagic.ComagicService.PushOfflineMessagesToBQ:output_type -> comagic.PushOfflineMessagesToBQResponse
	8,  // 12: comagic.ComagicService.GetCampaigns:output_type -> comagic.GetCampaignsResponse
	10, // 13: comagic.ComagicService.GetCampaignsConditions:output_type -> comagic.GetCampaignsConditionsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_grpc_comagic_proto_init() }
func file_api_grpc_comagic_proto_init() {
	if File_api_grpc_comagic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_comagic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCallsToBQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCallsToBQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOfflineMessagesToBQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOfflineMessagesToBQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsConditionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsConditionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_comagic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_comagic_proto_goTypes,
		DependencyIndexes: file_api_grpc_comagic_proto_depIdxs,
		MessageInfos:      file_api_grpc_comagic_proto_msgTypes,
	}.Build()
	File_api_grpc_comagic_proto = out.File
	file_api_grpc_comagic_proto_rawDesc = nil
	file_api_grpc_comagic_proto_goTypes = nil
	file_api_grpc_comagic_proto_depIdxs = nil
}
