// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/grpc/comagic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BqConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectID  string `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	DatasetID  string `protobuf:"bytes,2,opt,name=datasetID,proto3" json:"datasetID,omitempty"`
	TableID    string `protobuf:"bytes,3,opt,name=tableID,proto3" json:"tableID,omitempty"`
	ServiceKey string `protobuf:"bytes,4,opt,name=serviceKey,proto3" json:"serviceKey,omitempty"`
}

func (x *BqConfig) Reset() {
	*x = BqConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqConfig) ProtoMessage() {}

func (x *BqConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqConfig.ProtoReflect.Descriptor instead.
func (*BqConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{0}
}

func (x *BqConfig) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *BqConfig) GetDatasetID() string {
	if x != nil {
		return x.DatasetID
	}
	return ""
}

func (x *BqConfig) GetTableID() string {
	if x != nil {
		return x.TableID
	}
	return ""
}

func (x *BqConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

type CsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceKey string `protobuf:"bytes,1,opt,name=serviceKey,proto3" json:"serviceKey,omitempty"`
	BucketName string `protobuf:"bytes,2,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
}

func (x *CsConfig) Reset() {
	*x = CsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsConfig) ProtoMessage() {}

func (x *CsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsConfig.ProtoReflect.Descriptor instead.
func (*CsConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{1}
}

func (x *CsConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *CsConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type PushCallsToBQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string    `protobuf:"bytes,1,opt,name=comagicToken,proto3" json:"comagicToken,omitempty"`
	BqConfig     *BqConfig `protobuf:"bytes,2,opt,name=bqConfig,proto3" json:"bqConfig,omitempty"`
	CsConfig     *CsConfig `protobuf:"bytes,3,opt,name=csConfig,proto3" json:"csConfig,omitempty"`
	// dateFrom is date represented in the ISO-8601 format
	DateFrom string `protobuf:"bytes,4,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	// dateTill is date represented in the ISO-8601 format
	DateTill string `protobuf:"bytes,5,opt,name=dateTill,proto3" json:"dateTill,omitempty"`
}

func (x *PushCallsToBQRequest) Reset() {
	*x = PushCallsToBQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCallsToBQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCallsToBQRequest) ProtoMessage() {}

func (x *PushCallsToBQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCallsToBQRequest.ProtoReflect.Descriptor instead.
func (*PushCallsToBQRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{2}
}

func (x *PushCallsToBQRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

func (x *PushCallsToBQRequest) GetBqConfig() *BqConfig {
	if x != nil {
		return x.BqConfig
	}
	return nil
}

func (x *PushCallsToBQRequest) GetCsConfig() *CsConfig {
	if x != nil {
		return x.CsConfig
	}
	return nil
}

func (x *PushCallsToBQRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *PushCallsToBQRequest) GetDateTill() string {
	if x != nil {
		return x.DateTill
	}
	return ""
}

type PushCallsToBQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOK bool `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
}

func (x *PushCallsToBQResponse) Reset() {
	*x = PushCallsToBQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCallsToBQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCallsToBQResponse) ProtoMessage() {}

func (x *PushCallsToBQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCallsToBQResponse.ProtoReflect.Descriptor instead.
func (*PushCallsToBQResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{3}
}

func (x *PushCallsToBQResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

type PushOfflineMessagesToBQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string    `protobuf:"bytes,1,opt,name=comagicToken,proto3" json:"comagicToken,omitempty"`
	BqConfig     *BqConfig `protobuf:"bytes,2,opt,name=bqConfig,proto3" json:"bqConfig,omitempty"`
	CsConfig     *CsConfig `protobuf:"bytes,3,opt,name=csConfig,proto3" json:"csConfig,omitempty"`
	// dateFrom is date represented in the ISO-8601 format
	DateFrom string `protobuf:"bytes,4,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	// dateTill is date represented in the ISO-8601 format
	DateTill string `protobuf:"bytes,5,opt,name=dateTill,proto3" json:"dateTill,omitempty"`
}

func (x *PushOfflineMessagesToBQRequest) Reset() {
	*x = PushOfflineMessagesToBQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOfflineMessagesToBQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOfflineMessagesToBQRequest) ProtoMessage() {}

func (x *PushOfflineMessagesToBQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOfflineMessagesToBQRequest.ProtoReflect.Descriptor instead.
func (*PushOfflineMessagesToBQRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{4}
}

func (x *PushOfflineMessagesToBQRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

func (x *PushOfflineMessagesToBQRequest) GetBqConfig() *BqConfig {
	if x != nil {
		return x.BqConfig
	}
	return nil
}

func (x *PushOfflineMessagesToBQRequest) GetCsConfig() *CsConfig {
	if x != nil {
		return x.CsConfig
	}
	return nil
}

func (x *PushOfflineMessagesToBQRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *PushOfflineMessagesToBQRequest) GetDateTill() string {
	if x != nil {
		return x.DateTill
	}
	return ""
}

type PushOfflineMessagesToBQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOK bool `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
}

func (x *PushOfflineMessagesToBQResponse) Reset() {
	*x = PushOfflineMessagesToBQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOfflineMessagesToBQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOfflineMessagesToBQResponse) ProtoMessage() {}

func (x *PushOfflineMessagesToBQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOfflineMessagesToBQResponse.ProtoReflect.Descriptor instead.
func (*PushOfflineMessagesToBQResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{5}
}

func (x *PushOfflineMessagesToBQResponse) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

type GetCampaignsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string `protobuf:"bytes,1,opt,name=comagicToken,proto3" json:"comagicToken,omitempty"`
}

func (x *GetCampaignsRequest) Reset() {
	*x = GetCampaignsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsRequest) ProtoMessage() {}

func (x *GetCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{6}
}

func (x *GetCampaignsRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

type GetCampaignsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCampaignsResponse) Reset() {
	*x = GetCampaignsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsResponse) ProtoMessage() {}

func (x *GetCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{7}
}

type GetCampaignsConditionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComagicToken string `protobuf:"bytes,1,opt,name=comagicToken,proto3" json:"comagicToken,omitempty"`
}

func (x *GetCampaignsConditionsRequest) Reset() {
	*x = GetCampaignsConditionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsConditionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsConditionsRequest) ProtoMessage() {}

func (x *GetCampaignsConditionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsConditionsRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignsConditionsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{8}
}

func (x *GetCampaignsConditionsRequest) GetComagicToken() string {
	if x != nil {
		return x.ComagicToken
	}
	return ""
}

type GetCampaignsConditionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCampaignsConditionsResponse) Reset() {
	*x = GetCampaignsConditionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_comagic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCampaignsConditionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsConditionsResponse) ProtoMessage() {}

func (x *GetCampaignsConditionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_comagic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsConditionsResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignsConditionsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_comagic_proto_rawDescGZIP(), []int{9}
}

var File_api_grpc_comagic_proto protoreflect.FileDescriptor

var file_api_grpc_comagic_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x08, 0x42, 0x71, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x4a, 0x0a, 0x08, 0x43,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x14, 0x50, 0x75, 0x73, 0x68,
	0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x0a, 0x08, 0x62, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x08, 0x62, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x25, 0x0a, 0x08, 0x63,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x43, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x6c, 0x22, 0x2b, 0x0a, 0x15, 0x50, 0x75,
	0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x22, 0xca, 0x01, 0x0a, 0x1e, 0x50, 0x75, 0x73, 0x68,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54,
	0x6f, 0x42, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f,
	0x6d, 0x61, 0x67, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25,
	0x0a, 0x08, 0x62, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x62, 0x71, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x73, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x08, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6c, 0x6c, 0x22, 0x35, 0x0a, 0x1f, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x22, 0x39, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d,
	0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69,
	0x67, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc6, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68,
	0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x12, 0x15, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x6f, 0x42, 0x51,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x17, 0x50, 0x75, 0x73, 0x68,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54,
	0x6f, 0x42, 0x51, 0x12, 0x1f, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d,
	0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69,
	0x67, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_comagic_proto_rawDescOnce sync.Once
	file_api_grpc_comagic_proto_rawDescData = file_api_grpc_comagic_proto_rawDesc
)

func file_api_grpc_comagic_proto_rawDescGZIP() []byte {
	file_api_grpc_comagic_proto_rawDescOnce.Do(func() {
		file_api_grpc_comagic_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_comagic_proto_rawDescData)
	})
	return file_api_grpc_comagic_proto_rawDescData
}

var file_api_grpc_comagic_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_grpc_comagic_proto_goTypes = []interface{}{
	(*BqConfig)(nil),                        // 0: BqConfig
	(*CsConfig)(nil),                        // 1: CsConfig
	(*PushCallsToBQRequest)(nil),            // 2: PushCallsToBQRequest
	(*PushCallsToBQResponse)(nil),           // 3: PushCallsToBQResponse
	(*PushOfflineMessagesToBQRequest)(nil),  // 4: PushOfflineMessagesToBQRequest
	(*PushOfflineMessagesToBQResponse)(nil), // 5: PushOfflineMessagesToBQResponse
	(*GetCampaignsRequest)(nil),             // 6: GetCampaignsRequest
	(*GetCampaignsResponse)(nil),            // 7: GetCampaignsResponse
	(*GetCampaignsConditionsRequest)(nil),   // 8: GetCampaignsConditionsRequest
	(*GetCampaignsConditionsResponse)(nil),  // 9: GetCampaignsConditionsResponse
}
var file_api_grpc_comagic_proto_depIdxs = []int32{
	0, // 0: PushCallsToBQRequest.bqConfig:type_name -> BqConfig
	1, // 1: PushCallsToBQRequest.csConfig:type_name -> CsConfig
	0, // 2: PushOfflineMessagesToBQRequest.bqConfig:type_name -> BqConfig
	1, // 3: PushOfflineMessagesToBQRequest.csConfig:type_name -> CsConfig
	2, // 4: ComagicService.PushCallsToBQ:input_type -> PushCallsToBQRequest
	4, // 5: ComagicService.PushOfflineMessagesToBQ:input_type -> PushOfflineMessagesToBQRequest
	6, // 6: ComagicService.GetCampaigns:input_type -> GetCampaignsRequest
	8, // 7: ComagicService.GetCampaignsConditions:input_type -> GetCampaignsConditionsRequest
	3, // 8: ComagicService.PushCallsToBQ:output_type -> PushCallsToBQResponse
	5, // 9: ComagicService.PushOfflineMessagesToBQ:output_type -> PushOfflineMessagesToBQResponse
	7, // 10: ComagicService.GetCampaigns:output_type -> GetCampaignsResponse
	9, // 11: ComagicService.GetCampaignsConditions:output_type -> GetCampaignsConditionsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_grpc_comagic_proto_init() }
func file_api_grpc_comagic_proto_init() {
	if File_api_grpc_comagic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_comagic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCallsToBQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCallsToBQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOfflineMessagesToBQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOfflineMessagesToBQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsConditionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_comagic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCampaignsConditionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_comagic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_comagic_proto_goTypes,
		DependencyIndexes: file_api_grpc_comagic_proto_depIdxs,
		MessageInfos:      file_api_grpc_comagic_proto_msgTypes,
	}.Build()
	File_api_grpc_comagic_proto = out.File
	file_api_grpc_comagic_proto_rawDesc = nil
	file_api_grpc_comagic_proto_goTypes = nil
	file_api_grpc_comagic_proto_depIdxs = nil
}
